

type VehiclesCategories = {
    id: number,
    image: string,
    categorie: string,
    model: string,
    airConditioning: string,
    seats: number,
    doors: number,
    transmission: string,
    scooter: string,
    rentalPrice: string,
} 


export const Vehicle: VehiclesCategories[] = [
   {
     id: 0,
     image: "./images/Volkswagen-1.jpg",
     categorie: "SUV",
     model: "Volkswagen id 4",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Eletric",
     rentalPrice: "3,500 birr",
   },
   {
     id: 1,
     image: "./images/Hyundai-Elantra-1.jpg",
     categorie: "Compact",
     model: "Hyundia Elantra",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,500 birr",
   },
   {
     id: 2,
     image: "./images/Suzuki-Dzire-1.jpg",
     categorie: "Compact",
     model: "Suzuki Dsire",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,000 birr",
   },
   {
     id: 3,
     image: "./images/Toyota-Hilux-1.jpg",
     categorie: "Truck",
     model: "Toyota Hilux",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Manual",
     scooter: "Petrol",
     rentalPrice: "3,500 birr",
   },
   {
     id: 4,
     image: "./images/Jetour-Dashing-1.jpg",
     categorie: "SUV",
     model: "Jetour Dashing",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Hybrid",
     rentalPrice: "3,500 birr",
   },
   {
     id: 5,
     image: "./images/swift-1.jpg",
     categorie: "Economy",
     model: "Suzuki Swift",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,300 birr",
   },
   {
     id: 6,
     image: "./images/Toyota-Corolla-1.jpg",
     categorie: "Economy",
     model: "Toyota Corolla",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Manual",
     scooter: "Petrol",
     rentalPrice: "2,000 birr",
   },
   {
     id: 7,
     image: "./images/Hyundai-Tucson-1.jpg",
     categorie: "SUV",
     model: "Hyundai Tucson",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Hybrid",
     rentalPrice: "3,500 birr",
   },
   {
     id: 8,
     image: "./images/Honda-HR-1.jpg",
     categorie: "SUV",
     model: "Honda HR",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Hybrid",
     rentalPrice: "3,000 birr",
   },
   {
     id: 9,
     image: "./images/Toyota-Yaris-2.jpg",
     categorie: "Economy",
     model: "Toyota Vitz",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,000 birr",
   },
   {
     id: 10,
     image: "./images/hyundai_grand-1.jpg",
     categorie: "Van",
     model: "Hyundai Grand Van",
     airConditioning: "Air Conditioning",
     seats: 12,
     doors: 3,
     transmission: "Manual",
     scooter: "Petrol",
     rentalPrice: "2,800 birr",
   },
   {
     id: 11,
     image: "./images/Hyundai-Elantra-2.jpg",
     categorie: "Compact",
     model: "Hyundai Elantra",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Hybrid",
     rentalPrice: "2,700 birr",
   },
   {
     id: 12,
     image: "./images/Toyota-Hilux-2.jpg",
     categorie: "Truck",
     model: "Toyota Hilux",
     airConditioning: "Air Conditioning",
     seats: 5,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,800 birr",
   },
   {
     id: 13,
     image: "./images/Toyota-Yaris-1.jpg",
     categorie: "Truck",
     model: "Toyota Yaris",
     airConditioning: "Air Conditioning",
     seats: 4,
     doors: 4,
     transmission: "Automatic",
     scooter: "Petrol",
     rentalPrice: "2,000 birr",
   },
];


export default Vehicle;
